spring:
  datasource:
    url: jdbc:h2:file:~/almacenBD
    username: user
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console